# ===============================
# LangGraph Customer Support Agent
# ===============================

input_schema:
  customer_name: str
  email: str
  query: str
  priority: str
  ticket_id: str

stages:
  - name: INTAKE
    mode: deterministic
    abilities:
      - accept_payload
    mcp_server: COMMON
    prompt: "Execute abilities in sequence to initialize state."

  - name: UNDERSTAND
    mode: deterministic
    abilities:
      - parse_request_text
      - extract_entities
    mapping:
      parse_request_text: COMMON
      extract_entities: ATLAS
    prompt: "Parse customer query and extract entities."

  - name: PREPARE
    mode: deterministic
    abilities:
      - normalize_fields
      - enrich_records
      - add_flags_calculations
    mapping:
      normalize_fields: COMMON
      enrich_records: ATLAS
      add_flags_calculations: COMMON
    prompt: "Normalize ticket fields, enrich with history, and compute SLA risks."

  - name: ASK
    mode: deterministic
    abilities:
      - clarify_question
    mcp_server: COMMON
    prompt: "Ask clarifying questions if query is ambiguous."

  - name: WAIT
    mode: deterministic
    abilities:
      - extract_answer
      - store_answer
    mcp_server: COMMON
    prompt: "Wait for customer answer and store it."

  - name: RETRIEVE
    mode: deterministic
    abilities:
      - knowledge_base_search
      - store_data
    mapping:
      knowledge_base_search: ATLAS
      store_data: COMMON
    prompt: "Retrieve relevant knowledge base data."

  - name: DECIDE
    mode: non-deterministic
    abilities:
      - solution_evaluation
      - escalation_decision
      - update_payload
    mapping:
      solution_evaluation: COMMON
      escalation_decision: ATLAS
      update_payload: COMMON
    prompt: "Score solutions and escalate if score < 90."

  - name: UPDATE
    mode: deterministic
    abilities:
      - update_ticket
      - close_ticket
    mcp_server: ATLAS
    prompt: "Update ticket status or close if resolved."

  - name: CREATE
    mode: deterministic
    abilities:
      - response_generation
    mcp_server: COMMON
    prompt: "Generate customer-facing response using LLM."

  - name: DO
    mode: deterministic
    abilities:
      - execute_api_calls
      - trigger_notifications
    mcp_server: ATLAS
    prompt: "Execute external API calls and notify customer."

  - name: COMPLETE
    mode: deterministic
    abilities:
      - output_payload
    mcp_server: COMMON
    prompt: "Output the final structured payload and mark completion."

edges:
  - [INTAKE, UNDERSTAND]
  - [UNDERSTAND, PREPARE]
  - [PREPARE, ASK]
  - [ASK, WAIT]
  - [WAIT, RETRIEVE]
  - [RETRIEVE, DECIDE]
  - [DECIDE, UPDATE]
  - [UPDATE, CREATE]
  - [CREATE, DO]
  - [DO, COMPLETE]
  - [COMPLETE, END]
